const houseRent = [
    {
        '_id': '01',
        'title':'Washington Avenue',
        'image':'https://i.ibb.co/t3V6h7s/Rectangle-394.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$194',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '02',
        'title': 'Family Apartment Three',
        'image': 'https://i.ibb.co/7nFgKt7/Rectangle-396.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$264',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '03',
        'title': 'Gorgeous house',
        'image': 'https://i.ibb.co/CsQrhRP/Rectangle-398.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$194',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '04',
        'title': 'Luxury villa',
        'image': 'https://i.ibb.co/3fGjqBQ/Rectangle-403.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$294',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '05',
        'title': 'Washington Avenue',
        'image': 'https://i.ibb.co/KXRDRKm/Rectangle-404.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$356',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '06',
        'title': 'Washington Avenue',
        'image': 'https://i.ibb.co/J5qjmJN/Rectangle-405.png',
        'insideRoomImageOne':'https://i.ibb.co/G9QF5YD/Rectangle-407.png', 
        'insideRoomImageTwo':'https://i.ibb.co/6P1r4QC/Rectangle-408.png', 
        'insideRoomImageThree':'https://i.ibb.co/52j44fG/Rectangle-409.png', 
        'insideRoomImageFour':'https://i.ibb.co/87ZFBp4/Rectangle-410.png', 
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$356',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    }
]

export default houseRent;